"use client";
import { Copy, Plus, Trash2 } from "lucide-react";
import { CalculatedRow, AssetRow, ProjectSummary } from "@/types";

const fmt = (n: number, decimals = 0) => new Intl.NumberFormat("zh-CN", { maximumFractionDigits: decimals, minimumFractionDigits: decimals }).format(n || 0);
const cols = ["业态", "建筑面积", "得房率", "销售面积", "销售单价", "单方成本", "单方地价分摊", "销售总额", "建安成本-合计", "管理费用", "销售费用", "增值税", "净利润", "单方成本（含销管费）", "单方利润", "操作"];
const colWidths = [145,75,70,80,75,75,80,82,84,70,70,65,80,94,80,60];
const rowTone = (kind: AssetRow["kind"]) => kind === "销售" ? "bg-emerald-50/60" : kind === "自持酒店" ? "bg-sky-50/70" : kind === "自持商业" ? "bg-indigo-50/60" : "bg-violet-50/60";
const stickyTone = (kind: AssetRow["kind"]) => kind === "销售" ? "bg-emerald-50" : kind === "自持酒店" ? "bg-sky-50" : kind === "自持商业" ? "bg-indigo-50" : "bg-violet-50";

export function EditableTable({ rows, summary, updateRow, addRow, duplicateRow, deleteRow }: {
  rows: CalculatedRow[]; summary: ProjectSummary; updateRow: (id: string, patch: Partial<AssetRow>) => void;
  addRow: () => void; duplicateRow: (id: string) => void; deleteRow: (id: string) => void;
}) {
  const editNum = (row: CalculatedRow, key: keyof AssetRow, nullable = false) => <input className="table-input" type="number" value={(row[key] as number | null) ?? ""} placeholder={nullable ? "自动" : "0"} onChange={e => updateRow(row.id, { [key]: e.target.value === "" && nullable ? null : Number(e.target.value) })} />;
  const editRate = (row: CalculatedRow) => <div className="relative"><input aria-label={`${row.name}得房率`} className="table-input pr-6" type="number" min="0" max="100" step="0.01" value={((row.efficiencyRate ?? (row.buildingArea ? row.saleArea / row.buildingArea : 0)) * 100).toFixed(2).replace(/\.00$/, "")} onChange={e => updateRow(row.id, { efficiencyRate: Number(e.target.value) / 100 })}/><span className="pointer-events-none absolute right-2 top-2.5 text-xs text-slate-400">%</span></div>;
  const changeKind = (row: CalculatedRow, kind: AssetRow["kind"]) => {
    const efficiencyRate = kind === "销售" && !(row.efficiencyRate && row.efficiencyRate > 0) ? 1 : (row.efficiencyRate || 0);
    updateRow(row.id, { kind, efficiencyRate, governmentArea: 0, saleArea: kind === "销售" ? row.buildingArea * efficiencyRate : 0 });
  };
  const totals = { buildingArea: rows.reduce((s,r)=>s+r.buildingArea,0), saleArea: rows.reduce((s,r)=>s+r.saleArea,0) };
  const allocatedLandCostTotal = rows.reduce((total,row)=>total+row.allocatedLandCost,0);
  const landAllocationBasis = rows.reduce((total,row)=>total+(/地库|地下(?:车库|室)?|车位|停车/.test(row.name)?0:row.kind==="销售"?row.saleArea:row.buildingArea),0);
  const allocatedLandUnitCost = landAllocationBasis ? allocatedLandCostTotal*10000/landAllocationBasis : 0;
  const salesProfitTotal = rows.reduce((total,row)=>total+(row.kind==="销售"?row.netProfit:0),0);
  const totalUnitProfit = totals.saleArea ? salesProfitTotal*10000/totals.saleArea : 0;
  return <div className="card overflow-hidden">
    <div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h2 className="font-semibold text-slate-900">投资测算主表</h2><p className="mt-1 text-xs text-slate-500">浅色单元格可编辑，所有结果实时重算 · 金额单位：万元</p></div><button className="btn no-print" onClick={addRow}><Plus size={16}/>新增业态</button></div>
    <div className="print-wide overflow-x-auto"><table className="min-w-[1305px] w-full table-fixed border-collapse text-xs"><colgroup>{colWidths.map((width,index)=><col key={index} style={{width}}/>)}</colgroup><thead><tr className="bg-slate-50">{cols.map((c,i)=><th key={c} className={`whitespace-normal border-b border-r border-slate-200 px-1 py-2.5 text-center text-[11px] font-semibold leading-tight text-slate-600 ${i===0?"sticky left-0 z-20 bg-slate-50":""}`}>{c}{[1,2,4,5].includes(i)?<span className="ml-0.5 text-teal-600">✎</span>:""}</th>)}</tr></thead>
      <tbody>{rows.map(row => <tr key={row.id} className={`${rowTone(row.kind)} hover:brightness-[.98]`}>
        <td className={`sticky left-0 z-10 border-b border-r border-slate-200 p-1 ${stickyTone(row.kind)}`}><div className="flex flex-col gap-1"><input aria-label={`${row.name}业态名称`} className="table-text h-7 px-1 text-xs" style={{minWidth:0}} value={row.name} onChange={e=>updateRow(row.id,{name:e.target.value})}/><select aria-label={`${row.name}业态分类`} className="w-full rounded border border-slate-200 bg-white px-1 py-1 text-[11px] outline-none focus:border-teal-500" value={row.kind} onChange={e=>changeKind(row,e.target.value as AssetRow["kind"])}>{["销售","自持酒店","自持商业","其他自持"].map(kind=><option key={kind} value={kind}>{kind}</option>)}</select></div></td>
        <td className="border-b border-r border-slate-200">{editNum(row,"buildingArea")}</td><td className="border-b border-r border-slate-200">{editRate(row)}</td><td className="border-b border-r border-slate-200 bg-slate-50/70 px-3 text-right tabular-nums" title="销售分类：建筑面积 × 得房率；其他分类为0">{fmt(row.saleArea,2)}</td><td className="border-b border-r border-slate-200">{editNum(row,"salePrice")}</td><td className="border-b border-r border-slate-200">{editNum(row,"unitCost")}</td><td className="border-b border-r border-amber-200 bg-amber-50/50 px-2 text-right font-medium tabular-nums" title="销售业态按销售面积、自持业态按建筑面积分摊；地库不参与，单位：元/㎡">{fmt(row.allocatedLandUnitCost,0)}</td>
        <td className="border-b border-r border-slate-200 px-2 text-right tabular-nums" title="销售面积 × 销售单价 ÷ 10000">{fmt(row.revenue,1)}</td><td className="border-b border-r border-slate-200 px-2 text-right font-medium tabular-nums">{fmt(row.totalConstructionCost,1)}</td>
        <td className="border-b border-r border-slate-200 px-3 text-right font-medium tabular-nums" title={row.saleArea>0?"货值 × 管理费率":"建安成本 × 管理费率"}>{fmt(row.managementFee,1)}</td><td className="border-b border-r border-slate-200 px-3 text-right font-medium tabular-nums" title={row.saleArea>0?"销售额 × 销售费率":"不可售业态销售费用为 0"}>{fmt(row.salesFee,1)}</td><td className="border-b border-r border-slate-200 px-3 text-right tabular-nums" title="含税销售额 ÷（1＋增值税率）× 增值税率">{fmt(row.vat,1)}</td><td className={`border-b border-r border-slate-200 px-3 text-right font-semibold tabular-nums ${row.kind!=="销售"?"text-slate-400":row.netProfit<0?"text-rose-600":"text-emerald-700"}`} title={row.kind==="销售"?"销售收入减建安、分摊地价、管理费、销售费、增值税及股东计息":"非销售业态不计算净利润"}>{row.kind==="销售"?fmt(row.netProfit,1):"—"}</td><td className="border-b border-r border-slate-200 px-3 text-right tabular-nums">{fmt(row.fullUnitCost,0)}</td><td className={`border-b border-r border-slate-200 px-2 text-right font-semibold tabular-nums ${row.kind!=="销售"?"text-slate-400":row.unitProfit<0?"text-rose-600":"text-emerald-700"}`} title="销售业态净利润 × 10000 ÷ 销售面积">{row.kind==="销售"?fmt(row.unitProfit,0):"—"}</td>
        <td className="border-b border-slate-200 px-2"><div className="flex justify-center gap-1"><button className="rounded p-2 text-slate-400 hover:bg-slate-100 hover:text-teal-700" onClick={()=>duplicateRow(row.id)} title="复制"><Copy size={15}/></button><button className="rounded p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600" onClick={()=>deleteRow(row.id)} title="删除"><Trash2 size={15}/></button></div></td>
      </tr>)}
      <tr className="bg-slate-200 font-semibold text-slate-900"><td className="sticky left-0 z-10 bg-slate-200 px-2 py-3 text-center">合计</td><td className="px-2 text-right">{fmt(totals.buildingArea)}</td><td/><td className="px-2 text-right">{fmt(totals.saleArea)}</td><td colSpan={2}/><td className="px-2 text-right text-amber-700">{fmt(allocatedLandUnitCost,0)}</td><td className="px-2 text-right">{fmt(summary.revenue,1)}</td><td className="px-2 text-right">{fmt(summary.totalConstructionCost,1)}</td><td className="px-2 text-right">{fmt(summary.managementFee,1)}</td><td className="px-2 text-right">{fmt(summary.salesFee,1)}</td><td className="px-2 text-right">{fmt(summary.vat,1)}</td><td className={`px-2 text-right ${summary.netProfit<0?"text-rose-700":"text-emerald-700"}`}>{fmt(summary.netProfit,1)}</td><td/><td className={`px-2 text-right ${totalUnitProfit<0?"text-rose-700":"text-emerald-700"}`}>{fmt(totalUnitProfit,0)}</td><td/></tr>
      </tbody></table></div>
  </div>;
}
