"use client";
import { Copy, Plus, Trash2 } from "lucide-react";
import { CalculatedRow, AssetRow, ProjectSummary } from "@/types";

const fmt = (n: number, decimals = 0) => new Intl.NumberFormat("zh-CN", { maximumFractionDigits: decimals, minimumFractionDigits: decimals }).format(n || 0);
const cols = ["业态", "建筑面积", "给政府面积", "得房率", "销售面积", "销售单价", "单方成本", "销售总额", "建安成本-合计", "管理费用", "销售费用", "增值税", "净利润", "单方成本（含销管费）", "操作"];

export function EditableTable({ rows, summary, updateRow, addRow, duplicateRow, deleteRow }: {
  rows: CalculatedRow[]; summary: ProjectSummary; updateRow: (id: string, patch: Partial<AssetRow>) => void;
  addRow: () => void; duplicateRow: (id: string) => void; deleteRow: (id: string) => void;
}) {
  const editNum = (row: CalculatedRow, key: keyof AssetRow, nullable = false) => <input className="table-input" type="number" value={(row[key] as number | null) ?? ""} placeholder={nullable ? "自动" : "0"} onChange={e => updateRow(row.id, { [key]: e.target.value === "" && nullable ? null : Number(e.target.value) })} />;
  const editRate = (row: CalculatedRow) => <div className="relative"><input aria-label={`${row.name}得房率`} className="table-input pr-6" type="number" min="0" max="100" step="0.01" value={((row.efficiencyRate ?? (row.buildingArea ? row.saleArea / row.buildingArea : 0)) * 100).toFixed(2).replace(/\.00$/, "")} onChange={e => updateRow(row.id, { efficiencyRate: Number(e.target.value) / 100 })}/><span className="pointer-events-none absolute right-2 top-2.5 text-xs text-slate-400">%</span></div>;
  const changeKind = (row: CalculatedRow, kind: AssetRow["kind"]) => {
    const efficiencyRate = kind === "销售" && !(row.efficiencyRate && row.efficiencyRate > 0) ? 1 : (row.efficiencyRate || 0);
    updateRow(row.id, { kind, efficiencyRate, governmentArea: kind === "给政府" ? row.buildingArea : 0, saleArea: kind === "销售" ? row.buildingArea * efficiencyRate : 0 });
  };
  const totals = { buildingArea: rows.reduce((s,r)=>s+r.buildingArea,0), saleArea: rows.reduce((s,r)=>s+r.saleArea,0) };
  const above = rows.filter(r=>r.name.trim()!=="车位");
  const sub = (key:keyof CalculatedRow) => above.reduce((s,r)=>s+(typeof r[key]==="number"?r[key] as number:0),0);
  return <div className="card overflow-hidden">
    <div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h2 className="font-semibold text-slate-900">投资测算主表</h2><p className="mt-1 text-xs text-slate-500">浅色单元格可编辑，所有结果实时重算 · 金额单位：万元</p></div><button className="btn no-print" onClick={addRow}><Plus size={16}/>新增业态</button></div>
    <div className="print-wide overflow-x-auto"><table className="min-w-[1650px] w-full border-collapse text-sm"><thead><tr className="bg-slate-50">{cols.map((c,i)=><th key={c} className={`whitespace-nowrap border-b border-r border-slate-200 px-2 py-3 text-center text-xs font-semibold text-slate-600 ${i===0?"sticky left-0 z-20 bg-slate-50":""}`}>{c}{[1,3,5,6].includes(i)?<span className="ml-1 text-teal-600">✎</span>:""}</th>)}</tr></thead>
      <tbody>{rows.map(row => <tr key={row.id} className={`${row.kind === "给政府" ? "bg-amber-50" : row.kind.startsWith("自持") || row.kind === "其他自持" ? "bg-sky-50/60" : "bg-white"} hover:brightness-[.98]`}>
        <td className={`sticky left-0 z-10 border-b border-r border-slate-200 ${row.kind === "给政府" ? "bg-amber-50" : row.kind.startsWith("自持") || row.kind === "其他自持" ? "bg-sky-50" : "bg-white"}`}><div className="flex items-center gap-1"><input aria-label={`${row.name}业态名称`} className="table-text min-w-[110px]" value={row.name} onChange={e=>updateRow(row.id,{name:e.target.value})}/><select aria-label={`${row.name}业态分类`} className="mr-2 min-w-[96px] rounded border border-slate-200 bg-white px-1 py-1.5 text-xs outline-none focus:border-teal-500" value={row.kind} onChange={e=>changeKind(row,e.target.value as AssetRow["kind"])}>{["销售","自持酒店","自持商业","给政府","其他自持"].map(kind=><option key={kind} value={kind}>{kind}</option>)}</select></div></td>
        <td className="border-b border-r border-slate-200">{editNum(row,"buildingArea")}</td><td className="border-b border-r border-amber-200 bg-amber-50/70 px-3 text-right tabular-nums" title="选择“给政府”后自动等于建筑面积，其他分类自动为0">{fmt(row.governmentArea,2)}</td><td className="border-b border-r border-slate-200">{editRate(row)}</td><td className="border-b border-r border-slate-200 bg-slate-50/70 px-3 text-right tabular-nums" title="销售分类：建筑面积 × 得房率；其他分类为0">{fmt(row.saleArea,2)}</td><td className="border-b border-r border-slate-200">{editNum(row,"salePrice")}</td><td className="border-b border-r border-slate-200">{editNum(row,"unitCost")}</td>
        <td className="border-b border-r border-slate-200 px-2 text-right tabular-nums" title="销售面积 × 销售单价 ÷ 10000">{fmt(row.revenue,1)}</td><td className="border-b border-r border-slate-200 px-2 text-right font-medium tabular-nums">{fmt(row.totalConstructionCost,1)}</td>
        <td className="border-b border-r border-slate-200 px-3 text-right font-medium tabular-nums" title={row.saleArea>0?"货值 × 管理费率":"建安成本 × 管理费率"}>{fmt(row.managementFee,1)}</td><td className="border-b border-r border-slate-200 px-3 text-right font-medium tabular-nums" title={row.saleArea>0?"销售额 × 销售费率":"不可售业态销售费用为 0"}>{fmt(row.salesFee,1)}</td><td className="border-b border-r border-slate-200 px-3 text-right tabular-nums">{fmt(row.vat,1)}</td><td className={`border-b border-r border-slate-200 px-3 text-right font-semibold tabular-nums ${row.netProfit<0?"text-rose-600":"text-emerald-700"}`}>{fmt(row.netProfit,1)}</td><td className="border-b border-r border-slate-200 px-3 text-right tabular-nums">{fmt(row.fullUnitCost,0)}</td>
        <td className="border-b border-slate-200 px-2"><div className="flex justify-center gap-1"><button className="rounded p-2 text-slate-400 hover:bg-slate-100 hover:text-teal-700" onClick={()=>duplicateRow(row.id)} title="复制"><Copy size={15}/></button><button className="rounded p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600" onClick={()=>deleteRow(row.id)} title="删除"><Trash2 size={15}/></button></div></td>
      </tr>)}
      <tr className="bg-slate-100 font-medium text-slate-700"><td className="sticky left-0 z-10 bg-slate-100 px-2 py-2 text-center">地上小计</td><td className="px-2 text-right">{fmt(sub("buildingArea"))}</td><td className="px-2 text-right text-amber-700">{fmt(sub("governmentArea"))}</td><td/><td className="px-2 text-right">{fmt(sub("saleArea"))}</td><td colSpan={2}/><td className="px-2 text-right">{fmt(sub("revenue"),1)}</td><td className="px-2 text-right">{fmt(sub("totalConstructionCost"),1)}</td><td className="px-2 text-right">{fmt(sub("managementFee"),1)}</td><td className="px-2 text-right">{fmt(sub("salesFee"),1)}</td><td className="px-2 text-right">{fmt(sub("vat"),1)}</td><td className={`px-2 text-right ${sub("netProfit")<0?"text-rose-700":"text-emerald-700"}`}>{fmt(sub("netProfit"),1)}</td><td colSpan={2}/></tr>
      <tr className="bg-slate-200 font-semibold text-slate-900"><td className="sticky left-0 z-10 bg-slate-200 px-2 py-3 text-center">合计</td><td className="px-2 text-right">{fmt(totals.buildingArea)}</td><td className="px-2 text-right text-amber-700">{fmt(summary.governmentArea)}</td><td/><td className="px-2 text-right">{fmt(totals.saleArea)}</td><td colSpan={2}/><td className="px-2 text-right">{fmt(summary.revenue,1)}</td><td className="px-2 text-right">{fmt(summary.totalConstructionCost,1)}</td><td className="px-2 text-right">{fmt(summary.managementFee,1)}</td><td className="px-2 text-right">{fmt(summary.salesFee,1)}</td><td className="px-2 text-right">{fmt(summary.vat,1)}</td><td className={`px-2 text-right ${summary.netProfit<0?"text-rose-700":"text-emerald-700"}`}>{fmt(summary.netProfit,1)}</td><td colSpan={2}/></tr>
      </tbody></table></div>
  </div>;
}
