"use client";
import { useState } from "react";
import { Copy, GripVertical, Plus, Trash2 } from "lucide-react";
import { CalculatedRow, AssetRow, ProjectSummary } from "@/types";
import { isBasementOrParking } from "@/lib/calculationEngine";
import { NumericInput } from "@/components/NumericInput";

const fmt = (n: number, decimals = 0) => new Intl.NumberFormat("zh-CN", { maximumFractionDigits: decimals, minimumFractionDigits: decimals }).format(n || 0);
const governmentCols = ["业态", "建筑面积", "总套数", "给政府面积", "得房率", "销售面积", "销售单价", "单方成本", "单方分摊地价", "单方成本（含销管费）", "单方利润", "销售总额", "建安成本-合计", "管理费用", "销售费用", "增值税", "开办费", "净利润", "操作"];
const governmentColWidths = [145,75,70,75,70,80,75,75,80,94,80,82,84,70,70,65,70,80,60];
const rowTone = (kind: AssetRow["kind"]) => kind === "销售" ? "bg-emerald-50/60" : kind === "自持酒店" ? "bg-sky-50/70" : kind === "自持商业" ? "bg-indigo-50/60" : kind === "给政府" ? "bg-amber-50/80" : "bg-violet-50/60";
const stickyTone = (kind: AssetRow["kind"]) => kind === "销售" ? "bg-emerald-50" : kind === "自持酒店" ? "bg-sky-50" : kind === "自持商业" ? "bg-indigo-50" : kind === "给政府" ? "bg-amber-50" : "bg-violet-50";

export function EditableTable({ rows, summary, updateRow, addRow, duplicateRow, deleteRow, reorderRow }: {
  rows: CalculatedRow[]; summary: ProjectSummary; updateRow: (id: string, patch: Partial<AssetRow>) => void;
  addRow: () => void; duplicateRow: (id: string) => void; deleteRow: (id: string) => void; reorderRow: (sourceId: string, targetId: string) => void;
}) {
  const [draggedId, setDraggedId] = useState<string|null>(null);
  const [dragOverId, setDragOverId] = useState<string|null>(null);
  const [saleAreaDrafts, setSaleAreaDrafts] = useState<Record<string,string>>({});
  const governmentMode = rows.some(row => row.kind === "给政府");
  const cols = governmentMode ? governmentCols : governmentCols.filter((_, index) => index !== 3);
  const colWidths = governmentMode ? governmentColWidths : governmentColWidths.filter((_, index) => index !== 3);
  const editNum = (row: CalculatedRow, key: keyof AssetRow) => <NumericInput className="table-input" value={row[key] as number | null} placeholder="0" onValueChange={value => updateRow(row.id, { [key]: value })} onEmpty={() => updateRow(row.id, { [key]: 0 })} />;
  const editUnitCount = (row: CalculatedRow) => <NumericInput className="table-input" value={row.unitCount} placeholder="手动输入" onValueChange={value => updateRow(row.id, { unitCount: Math.max(0, Math.round(value)) })} onEmpty={() => updateRow(row.id, { unitCount: undefined })} />;
  const editRate = (row: CalculatedRow) => <div className="relative"><NumericInput aria-label={`${row.name}得房率`} className="table-input !pr-8" value={(row.efficiencyRate ?? (row.buildingArea ? row.saleArea / row.buildingArea : 0)) * 100} formatValue={value => Number(value ?? 0).toFixed(2).replace(/\.00$/, "")} onValueChange={value => updateRow(row.id, { efficiencyRate: Math.max(0, Math.min(100, value)) / 100 })} onEmpty={() => updateRow(row.id, { efficiencyRate: 0 })}/><span className="pointer-events-none absolute right-2 top-1/2 w-3 -translate-y-1/2 text-center text-xs text-slate-400">%</span></div>;
  const saleAreaText = (value: number) => Number.isInteger(value || 0) ? String(value || 0) : String(Number((value || 0).toFixed(4)));
  const editSaleArea = (row: CalculatedRow) => row.kind === "销售" ? <input className="table-input" type="text" inputMode="decimal" value={saleAreaDrafts[row.id] ?? saleAreaText(row.saleArea)} onChange={e => { const raw = e.target.value; if (!/^\d*\.?\d*$/.test(raw)) return; setSaleAreaDrafts(drafts => ({ ...drafts, [row.id]: raw })); if (raw === "" || raw === ".") return; const saleArea = Math.max(0, Number(raw)); updateRow(row.id, { saleArea, efficiencyRate: row.buildingArea > 0 ? saleArea / row.buildingArea : 0 }); }} onBlur={() => setSaleAreaDrafts(drafts => { const next = { ...drafts }; delete next[row.id]; return next; })} /> : <div className="bg-slate-50/70 px-3 text-right tabular-nums text-slate-400" title="非销售业态销售面积为0">{fmt(row.saleArea)}</div>;
  const changeKind = (row: CalculatedRow, kind: AssetRow["kind"]) => {
    const efficiencyRate = kind === "销售" && !(row.efficiencyRate && row.efficiencyRate > 0) ? 1 : (row.efficiencyRate || 0);
    updateRow(row.id, { kind, efficiencyRate, governmentArea: kind === "给政府" ? row.buildingArea : 0, saleArea: kind === "销售" ? row.buildingArea * efficiencyRate : 0 });
  };
  const totals = { buildingArea: rows.reduce((s,r)=>s+r.buildingArea,0), saleArea: rows.reduce((s,r)=>s+r.saleArea,0) };
  const allocatedLandCostTotal = rows.reduce((total,row)=>total+row.allocatedLandCost,0);
  const allocationBasisTotal = governmentMode ? totals.saleArea : rows.reduce((total,row)=>total+(isBasementOrParking(row)?0:row.kind==="销售"?row.saleArea:row.kind!=="给政府"?row.buildingArea:0),0);
  const allocatedLandUnitCost = allocationBasisTotal ? allocatedLandCostTotal*10000/allocationBasisTotal : 0;
  const averageSalePrice = totals.saleArea ? rows.reduce((total,row)=>total+(row.kind==="销售"?row.saleArea*row.salePrice:0),0)/totals.saleArea : 0;
  const salesProfitTotal = rows.reduce((total,row)=>total+(row.kind==="销售"?row.netProfit:0),0);
  const totalUnitProfit = totals.saleArea ? salesProfitTotal*10000/totals.saleArea : 0;
  return <div className="card overflow-hidden">
    <div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h2 className="font-semibold text-slate-900">投资测算主表</h2><p className="mt-1 text-xs text-slate-500">浅色单元格可编辑，拖动业态名称左侧手柄可排序 · 金额单位：万元</p></div><button className="btn no-print" onClick={addRow}><Plus size={16}/>新增业态</button></div>
    <div className="print-wide overflow-x-auto"><table className={`${governmentMode?"min-w-[1520px]":"min-w-[1445px]"} w-full table-fixed border-collapse text-xs`}><colgroup>{colWidths.map((width,index)=><col key={index} style={{width}}/>)}</colgroup><thead><tr className="bg-slate-50">{cols.map((c,i)=><th key={c} className={`whitespace-normal border-b border-r border-slate-200 px-1 py-2.5 text-center text-[11px] font-semibold leading-tight text-slate-600 ${i===0?"sticky left-0 z-20 bg-slate-50":""}`}>{c}{(governmentMode?[1,2,4,5,6,7]:[1,2,3,4,5,6]).includes(i)?<span className="ml-0.5 text-teal-600">✎</span>:""}</th>)}</tr></thead>
      <tbody>{rows.map(row => <tr key={row.id} onDragOver={event=>{if(draggedId&&draggedId!==row.id){event.preventDefault();event.dataTransfer.dropEffect="move";setDragOverId(row.id);}}} onDrop={event=>{event.preventDefault();if(draggedId&&draggedId!==row.id)reorderRow(draggedId,row.id);setDraggedId(null);setDragOverId(null);}} className={`${rowTone(row.kind)} hover:brightness-[.98] ${draggedId===row.id?"opacity-45":""} ${dragOverId===row.id?"outline outline-2 outline-offset-[-2px] outline-teal-500":""}`}>
        <td className={`sticky left-0 z-10 border-b border-r border-slate-200 p-1 ${stickyTone(row.kind)}`}><div className="flex flex-col gap-1"><div className="flex min-w-0 items-center"><button type="button" draggable aria-label={`拖动${row.name}调整顺序`} title="按住拖动调整顺序" className="no-print shrink-0 cursor-grab touch-none rounded p-0.5 text-slate-400 hover:bg-white/70 hover:text-teal-700 active:cursor-grabbing" onDragStart={event=>{setDraggedId(row.id);setDragOverId(null);event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",row.id);}} onDragEnd={()=>{setDraggedId(null);setDragOverId(null);}}><GripVertical size={14}/></button><input aria-label={`${row.name}业态名称`} className="table-text h-7 min-w-0 px-1 text-xs" style={{minWidth:0}} value={row.name} onChange={e=>updateRow(row.id,{name:e.target.value})}/></div><select aria-label={`${row.name}业态分类`} className="w-full rounded border border-slate-200 bg-white px-1 py-1 text-[11px] outline-none focus:border-teal-500" value={row.kind} onChange={e=>changeKind(row,e.target.value as AssetRow["kind"])}>{["销售","自持酒店","自持商业","给政府","其他自持"].map(kind=><option key={kind} value={kind}>{kind}</option>)}</select></div></td>
        <td className="border-b border-r border-slate-200">{editNum(row,"buildingArea")}</td><td className="border-b border-r border-slate-200">{editUnitCount(row)}</td>{governmentMode&&<td className="border-b border-r border-amber-200 bg-amber-50/70 px-3 text-right tabular-nums" title="选择“给政府”后自动等于建筑面积，其他分类自动为0">{fmt(row.governmentArea)}</td>}<td className="border-b border-r border-slate-200">{editRate(row)}</td><td className="border-b border-r border-slate-200" title="销售业态可直接输入，并自动反算得房率">{editSaleArea(row)}</td><td className="border-b border-r border-slate-200">{editNum(row,"salePrice")}</td><td className="border-b border-r border-slate-200">{editNum(row,"unitCost")}</td><td className="border-b border-r border-slate-200 px-2 text-right font-medium tabular-nums" title={governmentMode?"给政府业态建安成本分摊总额 × 10000 ÷ 销售面积":"土地总价先按业态建筑面积分摊；可售业态按销售面积折单方，非可售按建筑面积折单方；地库、车位除外"}>{fmt(row.allocatedLandUnitCost)}</td><td className="border-b border-r border-slate-200 px-3 text-right tabular-nums" title="建安成本、分摊地价、开办费及销管费合计折算单方">{fmt(row.fullUnitCost)}</td><td className={`border-b border-r border-slate-200 px-2 text-right font-semibold tabular-nums ${row.kind!=="销售"?"text-slate-400":row.unitProfit<0?"text-rose-600":"text-emerald-700"}`} title="销售业态净利润 × 10000 ÷ 销售面积">{row.kind==="销售"?fmt(row.unitProfit):"—"}</td>
        <td className="border-b border-r border-slate-200 px-2 text-right tabular-nums" title="销售面积 × 销售单价 ×（1 - 全款比例 × 全款优惠比例）÷ 10000">{fmt(row.revenue)}</td><td className="border-b border-r border-slate-200 px-2 text-right font-medium tabular-nums" title="建筑面积 × 单方成本 ÷ 10000；给政府业态的给政府面积成本包含在本列内，不重复计算">{fmt(row.totalConstructionCost)}</td>
        <td className="border-b border-r border-slate-200 px-3 text-right font-medium tabular-nums" title={row.saleArea>0?"货值 × 管理费率":"建安成本 × 管理费率"}>{fmt(row.managementFee)}</td><td className="border-b border-r border-slate-200 px-3 text-right font-medium tabular-nums" title={row.saleArea>0?"销售额 × 销售费率":"不可售业态销售费用为 0"}>{fmt(row.salesFee)}</td><td className="border-b border-r border-slate-200 px-3 text-right tabular-nums" title="含税销售额 ÷（1＋增值税率）× 增值税率">{fmt(row.vat)}</td><td className="border-b border-r border-slate-200 px-3 text-right tabular-nums" title="酒店、MALL、会展/会议中心等按项目基础设置的开办费标准计算">{fmt(row.openingCost)}</td><td className={`border-b border-r border-slate-200 px-3 text-right font-semibold tabular-nums ${row.kind!=="销售"?"text-slate-400":row.netProfit<0?"text-rose-600":"text-emerald-700"}`} title={row.kind==="销售"?"销售收入减建安、分摊地价、开办费、管理费、销售费、增值税及股东计息":"非销售业态不计算净利润"}>{row.kind==="销售"?fmt(row.netProfit):"—"}</td>
        <td className="border-b border-slate-200 px-2"><div className="flex justify-center gap-1"><button className="rounded p-2 text-slate-400 hover:bg-slate-100 hover:text-teal-700" onClick={()=>duplicateRow(row.id)} title="复制"><Copy size={15}/></button><button className="rounded p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600" onClick={()=>deleteRow(row.id)} title="删除"><Trash2 size={15}/></button></div></td>
      </tr>)}
      <tr className="bg-slate-200 font-semibold text-slate-900"><td className="sticky left-0 z-10 bg-slate-200 px-2 py-3 text-center">合计</td><td className="px-2 text-right">{fmt(totals.buildingArea)}</td><td className="px-2 text-right">{fmt(rows.reduce((s,r)=>s+(r.unitCount||0),0))}</td>{governmentMode&&<td className="px-2 text-right text-amber-700">{fmt(summary.governmentArea)}</td>}<td/><td className="px-2 text-right">{fmt(totals.saleArea)}</td><td className="px-2 text-right" title="按销售面积加权平均">{fmt(averageSalePrice)}</td><td/><td className="px-2 text-right">{fmt(allocatedLandUnitCost)}</td><td/><td className={`px-2 text-right ${totalUnitProfit<0?"text-rose-700":"text-emerald-700"}`}>{fmt(totalUnitProfit)}</td><td className="px-2 text-right">{fmt(summary.revenue)}</td><td className="px-2 text-right">{fmt(summary.totalConstructionCost)}</td><td className="px-2 text-right">{fmt(summary.managementFee)}</td><td className="px-2 text-right">{fmt(summary.salesFee)}</td><td className="px-2 text-right">{fmt(summary.vat)}</td><td className="px-2 text-right">{fmt(summary.openingCost)}</td><td className={`px-2 text-right ${summary.netProfit<0?"text-rose-700":"text-emerald-700"}`}>{fmt(summary.netProfit)}</td><td/></tr>
      </tbody></table></div>
  </div>;
}
