"use client";
import { AssetRow, CalculatedRow, HoldingReturn } from "@/types";
const fmt=(n:number)=>new Intl.NumberFormat("zh-CN",{maximumFractionDigits:1}).format(n||0);
export function HoldingPanel({ rows, include, setInclude, updateRow }: { rows:CalculatedRow[];include:boolean;setInclude:(value:boolean)=>void;updateRow:(id:string,patch:Partial<AssetRow>)=>void }) {
  const held=rows.filter(r=>r.kind.startsWith("自持")||r.kind==="其他自持");
  const edit=(row:CalculatedRow,key:keyof HoldingReturn,percent=false)=><input className="table-input" type="number" value={percent?(row.holding?.[key]||0)*100:row.holding?.[key]||0} onChange={e=>updateRow(row.id,{holding:{...(row.holding||{annualRent:0,annualOperatingIncome:0,annualOperatingCost:0,holdingYears:10,discountRate:.08}),[key]:Number(e.target.value)/(percent?100:1)}})}/>;
  const auto=(value:number,title:string)=><div className="px-3 text-right font-medium tabular-nums" title={title}>{fmt(value)}</div>;
  return <section className="card overflow-hidden" id="holding"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-5 py-4"><div><h2 className="font-semibold text-slate-900">自持业态经营回报</h2><p className="mt-1 text-xs text-slate-500">酒店按客房数×房价×入住率，商业按面积×租金×出租率自动测算；金额单位：万元</p></div><label className="flex cursor-pointer items-center gap-2 text-sm"><input type="checkbox" checked={include} onChange={e=>setInclude(e.target.checked)} className="h-4 w-4 accent-teal-700"/>计入项目总收入</label></div>
    <div className="overflow-x-auto"><table className="min-w-[1350px] w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["业态","分类","客房数","年租金收入","年经营收入","年经营成本","年净现金流","持有年限","累计回报","折现率","NPV","IRR"].map(x=><th key={x} className="border-b border-r border-slate-200 px-3 py-3">{x}</th>)}</tr></thead><tbody>{held.map(row=><tr key={row.id} className="bg-sky-50/40"><td className="border-b border-r border-slate-200 px-3 font-medium">{row.name}</td><td className="border-b border-r border-slate-200 px-3 text-center text-xs text-sky-700">{row.kind}</td><td className="border-b border-r border-slate-200">{row.kind==="自持酒店"?edit(row,"roomCount"):<div className="px-3 text-center text-slate-300">—</div>}</td><td className="border-b border-r border-slate-200">{row.kind==="自持商业"?auto(row.holding?.annualRent||0,"按商业面积、月租金和出租率自动计算"):row.kind==="自持酒店"?auto(0,"酒店收入计入年经营收入"):edit(row,"annualRent")}</td><td className="border-b border-r border-slate-200">{row.kind==="自持酒店"?auto(row.holding?.annualOperatingIncome||0,"按客房数、平均房价和入住率自动计算"):row.kind==="自持商业"?auto(0,"商业收入计入年租金收入"):edit(row,"annualOperatingIncome")}</td><td className="border-b border-r border-slate-200">{auto(row.holding?.annualOperatingCost||0,"按年经营收入合计 × 年经营成本占比自动计算")}</td><td className="border-b border-r border-slate-200 px-3 text-right font-medium">{fmt(row.annualNetCashFlow)}</td><td className="border-b border-r border-slate-200">{edit(row,"holdingYears")}</td><td className="border-b border-r border-slate-200 px-3 text-right">{fmt(row.cumulativeReturn)}</td><td className="border-b border-r border-slate-200">{edit(row,"discountRate",true)}</td><td className={`border-b border-r border-slate-200 px-3 text-right ${row.npv<0?"text-rose-600":"text-emerald-700"}`}>{fmt(row.npv)}</td><td className="border-b border-slate-200 px-3 text-right">{row.irr===null?"—":`${(row.irr*100).toFixed(2)}%`}</td></tr>)}</tbody></table></div>
  </section>;
}
